name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        uses: Customis/huggingface-spaces-sync-action@v1.1.2
        with:
          github_repo: "ppsiakhaker/NAZWA_TWOJEGO_REPOZYTORIUM_NA_GITHUBIE"
          huggingface_repo: "psiak/NAZWA_TWOJEGO_PROJEKTU_NA_HF"
          hf_token: ${{ secrets.HF_TOKEN }}
          target_branch: "main"
